### ISSUE TITLE
Considering inclusion in Symfony?

### ISSUE THREAD

**Issue by welcoMattic** [m2mtech/weblate-translation-provider#7]
Would you consider the idea of adding the Weblate Translation Provider into Symfony core?
It could be listed in https://symfony.com/doc/current/translation.html#translation-providers, and benefit of the backward compatibility of Symfony.

I'll be happy to discuss it if you want :wink:

**Comment by m2mtech** [comment]
@welcoMattic sure, let's discuss ;)

**Comment by welcoMattic** [comment]
@m2mtech the first thing I see is you splitted Weblate API call into multiple files. For consistency, it should be in the same file, `WeblateProvider`, with well-named private methods. No matter the number of private methods.

DTOs are not mandatory I guess, it's fine to work with arrays. It could be discussed, if I miss something that deserve usage of DTO.

Otherwise, the Provider seems good, nice job :+1:

**Comment by m2mtech** [comment]
@welcoMattic Sorry, my mistake. It thought this would be a discussion about how a native symfony library differs from a 3rd-party one. e.g.

- where the actual library needs to move,
- how dependency injection is split between the FrameWork bundle and the translation component,
- how current users will be impacted by the change of the configuration namespace (are there flex provisions in place for an automatic migration?),
- where the documentation needs to move,
- future maintenance obligations of the library,
- and so on.

Instead, it turned out to be a philosophical discussion about patterns.

The library already has backward compatibility for php 7.2 and Symfony 5.3 - so I do not understand your initial argument either.
